export const environment = {
  production: true,
  apiUrl: '/api',
  appName: 'CDR Group',
  version: '1.0.0',
  defaultCompanyId: 'aabbccdd-aabb-aabb-aabb-aabbccddeeff',
  companyPreferenceCodes: [
    'NEWS_LABEL',
    'ABOUT_DESCRIPTION_TITLE',
    'SECONDARY_ABOUT_DESCRIPTION_TITLE',
    'SECONDARY_ABOUT_DESCRIPTION_SUB_TITLE',
    'MARKETING_TITLE',
    'MARKETING_DESCRIPTION',
    'COMPANY_CLIENT_REACHES_TITLE',
    'COMPANY_CLIENT_REACHES_DESCRIPTION',
    'FIRST_SECTION_ABOUT_COMPANY',
    'SECOND_SECTION_ABOUT_COMPANY',
    'COMPANY_FORMS_TITLE',
    'COMPANY_FORMS_DESCRIPTION',
    'COMPARISON_LEFT_TITLE',
    'COMPARISON_LEFT_CONTENT',
    'COMPARISON_RIGHT_TITLE',
    'COMPARISON_RIGHT_CONTENT',
    'COMPANY_GEOGRAPHIC_EXPANSIONS_TITLE',
    'COMPANY_GEOGRAPHIC_EXPANSIONS_DESCRIPTION',
    'WHAT_WE_DO_TITLE',
    'WHAT_WE_DO_DESCRIPTION',
    'SUCCESS_REASON_TITLE',
    'SUCCESS_REASON_DESCRIPTION',
    'WHEN_WHERE_TITLE',
    'WHEN_WHERE_DESCRIPTION',
    'DISTRIBUTION_MARKETING_TITLE',
    'DISTRIBUTION_MARKETING_DESCRIPTION',
    'DISTINGUISHES_TITLE',
    'DISTINGUISHES_DESCRIPTION',
    'PRE_CONTRACT_STUDIES_TITLE',
    'PRE_CONTRACT_STUDIES_DESCRIPTION',
    'PARTNERSHIP_FRANCHISE_MECHANISM_TITLE',
    'PARTNERSHIP_FRANCHISE_MECHANISM_DESCRIPTION',
  ],
  companyTitleDescriptionCodes: [
    'WHAT_WE_DO',
    'COMPANY_GEOGRAPHIC_EXPANSIONS',
    'WHEN_WHERE',
    'SUCCESS_REASON',
    'DISTRIBUTION_MARKETING',
    'DISTINGUISHES',
    'PRE_CONTRACT_STUDIES',
    'PARTNERSHIP_FRANCHISE_MECHANISM',
  ],
  componentCodes: [
    'app-about',
    'app-sub-companies',
    'app-branches',
    'app-card-scroller',
    'app-fill-cards',
    'app-quote-slider',
    'app-glass-slider',
    'app-image-title-slider',
    'app-promise-banner',
    'app-glass-card',
    'app-statement-slider',
    'app-client-reaches',
    'app-comparison',
    'app-forms',
    'app-events',
    'app-team',
    'app-contact-review',
  ]
};
