export const environment = {
  production: false,
  apiUrl: 'https://localhost:7240/api',
  appName: 'CDR Group',
  version: '1.0.0-dev',
  defaultCompanyId: 'aabbccdd-aabb-aabb-aabb-aabbccddeeff',
  companyPreferenceCodes: [
    'NEWS_LABEL',
    'ABOUT_DESCRIPTION_TITLE',
    'ABOUT_SECTION_HINT',
    'SECONDARY_ABOUT_DESCRIPTION_TITLE',
    'SECONDARY_ABOUT_DESCRIPTION_SUB_TITLE',
    'MARKETING_TITLE',
    'MARKETING_DESCRIPTION',
    'COMPANY_CLIENT_REACHES_TITLE',
    'COMPANY_CLIENT_REACHES_DESCRIPTION',
    'FIRST_SECTION_ABOUT_COMPANY',
    'SECOND_SECTION_ABOUT_COMPANY',
    'COMPANY_FORMS_TITLE',
    'COMPANY_FORMS_DESCRIPTION',
    'COMPARISON_LEFT_TITLE',
    'COMPARISON_LEFT_CONTENT',
    'COMPARISON_RIGHT_TITLE',
    'COMPARISON_RIGHT_CONTENT',
    'COMPANY_GEOGRAPHIC_EXPANSIONS_TITLE',
    'COMPANY_GEOGRAPHIC_EXPANSIONS_DESCRIPTION',
    'WHAT_WE_DO_TITLE',
    'WHAT_WE_DO_DESCRIPTION',
    'SUCCESS_REASON_TITLE',
    'SUCCESS_REASON_DESCRIPTION',
    'WHEN_WHERE_TITLE',
    'WHEN_WHERE_DESCRIPTION',
    'DISTRIBUTION_MARKETING_TITLE',
    'DISTRIBUTION_MARKETING_DESCRIPTION',
    'DISTINGUISHES_TITLE',
    'DISTINGUISHES_DESCRIPTION',
    'PRE_CONTRACT_STUDIES_TITLE',
    'PRE_CONTRACT_STUDIES_DESCRIPTION',
    'PARTNERSHIP_FRANCHISE_MECHANISM_TITLE',
    'PARTNERSHIP_FRANCHISE_MECHANISM_DESCRIPTION',
    'REELS_STARS_TITLE',
    'REELS_STARS_DESCRIPTION',
    'PROMISE_BANNER_TITLE',
    'PROMISE_BANNER_DESCRIPTION',
    'SUB_COMPANY_SECTION_DESCRIPTION',
    'CORE_OBJECTIVES_TITLE',
    'CORE_OBJECTIVES_DESCRIPTION',
    'FUTURE_ACHIEVEMENTS_TITLE',
    'FUTURE_ACHIEVEMENTS_DESCRIPTION',
    'OUR_PROCESS_TITLE',
    'OUR_PROCESS_DESCRIPTION',
    'OUR_VALUES_TITLE',
    'OUR_VALUES_DESCRIPTION'
  ],
  companyTitleDescriptionCodes: [
    'WHAT_WE_DO',
    'COMPANY_GEOGRAPHIC_EXPANSIONS',
    'WHEN_WHERE',
    'SUCCESS_REASON',
    'DISTRIBUTION_MARKETING',
    'DISTINGUISHES',
    'PRE_CONTRACT_STUDIES',
    'PARTNERSHIP_FRANCHISE_MECHANISM',
    'REELS_STARS',
    'CORE_OBJECTIVES',
    'FUTURE_ACHIEVEMENTS',
    'OUR_PROCESS',
    'OUR_VALUES'
  ],
  componentCodes: [
    'app-hub-header',
    'app-hero',
    'app-company-hub',
    'app-about',
    'app-sub-companies',
    'app-branches',
    'app-card-scroller',
    'app-fill-cards',
    'app-quote-slider',
    'app-glass-slider',
    'app-image-title-slider',
    'app-promise-banner',
    'app-glass-card',
    'app-statement-slider',
    'app-client-reaches',
    'app-comparison',
    'app-promise-banner',
    'app-forms',
    'app-events',
    'app-team',
    'app-contact-review',
    'app-hub-footer'
  ]
};
